server:
  port: 8082

dubbo:
  application:
    name: c
  registry:
    #注册中心地址
    address: zookeeper://192.168.0.109:2181
    #超时时间，毫秒
    timeout:
  protocol:
    #协议名称
    name: dubbo
    port: 20880
  scan:
    #扫描包位置
    base-packages: com.dubbo.c.apiimpl
